title: Yocto/GL
author: by Fabio Pellacini (xelatihy) and Collaborators
github_username: xelatihy
theme: minima
header_pages:
  - gallery.md
titles_from_headings:
  enabled:     true
  strip_title: true
