name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    before_script:
    - apt-get update --yes
    - apt-get install --yes cmake
    
    steps:
    - uses: actions/checkout@v1
    - name: cmake
      run: cmkae .
    - name: make
      run: make
