name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: |
        sudo apt-get update --yes
        sudo apt-get install --yes cmake
    - name: configure
      run: |
        mkdir build
        cd build
        cmake .. -DYOCTO_OPENGL=OFF -DYOCTO_EMBREE=OFF
    - name: build
      run: |
        cd build
        cmake --build .
